apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: selenium-hub
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444